package pe.edu.uni.proyectodeli.view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import pe.edu.uni.proyectodeli.controller.EnvioController;

import pe.edu.uni.proyectodeli.dto.ClienteDto;

public class RegistroEnvioView extends javax.swing.JDialog {

	private List<JLabel> listaLabels = new ArrayList<>();
	private List<JTextField> listaTextFields = new ArrayList<>();
	private List<JComboBox> listaCombo = new ArrayList<>();
	private ClienteDto clienteDto;

	public RegistroEnvioView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setLocationRelativeTo(null);
	}

	public void enable(Boolean flag) {
		listaLabels.forEach((jLabel) -> {
			jLabel.setEnabled(flag);
		});
		listaTextFields.forEach((jTextField) -> {
			jTextField.setEnabled(flag);
		});
		listaCombo.forEach((jComboBox) -> {
			jComboBox.setEnabled(flag);
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      txtAncho = new javax.swing.JTextField();
      txtLargo = new javax.swing.JTextField();
      jLabel20 = new javax.swing.JLabel();
      txtReceptorDNI = new javax.swing.JTextField();
      jLabel21 = new javax.swing.JLabel();
      txtReceptorCelular = new javax.swing.JTextField();
      btnConfirmar = new javax.swing.JButton();
      btnCancelar = new javax.swing.JButton();
      jLabel2 = new javax.swing.JLabel();
      jLabel25 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel29 = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      txtEmisorDNI = new javax.swing.JTextField();
      jLabel14 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jLabel15 = new javax.swing.JLabel();
      txtEmisorNombre = new javax.swing.JTextField();
      jLabel16 = new javax.swing.JLabel();
      jLabel17 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      txtReceptorApellidoP = new javax.swing.JTextField();
      txtReceptorApellidoM = new javax.swing.JTextField();
      jLabel5 = new javax.swing.JLabel();
      txtReceptorNombre = new javax.swing.JTextField();
      txtPeso = new javax.swing.JTextField();
      txtAlto = new javax.swing.JTextField();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      txtAncho.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      txtLargo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel20.setText("DNI");

      txtReceptorDNI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel21.setText("Celular");

      txtReceptorCelular.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      btnConfirmar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      btnConfirmar.setText("Confirmar");
      btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnConfirmarActionPerformed(evt);
         }
      });

      btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
      btnCancelar.setText("Cancelar");
      btnCancelar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarActionPerformed(evt);
         }
      });

      jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jLabel2.setText(" REGISTRO DEL ENVIO");

      jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jLabel25.setText("Emisor");

      jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jLabel7.setText("Datos del paquete");

      jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel29.setText("DNI");

      jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel13.setText("Largo");

      txtEmisorDNI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      txtEmisorDNI.addFocusListener(new java.awt.event.FocusAdapter() {
         public void focusLost(java.awt.event.FocusEvent evt) {
            txtEmisorDNIFocusLost(evt);
         }
      });

      jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel14.setText("Alto");

      jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel10.setText("Nombre Completo");

      jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel15.setText("Ancho");

      txtEmisorNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      txtEmisorNombre.setEnabled(false);

      jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel16.setText("Peso Kg");

      jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
      jLabel17.setText("¿Quien Recibe?");

      jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel9.setText("Apellidos");

      txtReceptorApellidoP.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      txtReceptorApellidoM.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel5.setText("Nombre");

      txtReceptorNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      txtPeso.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      txtAlto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jLabel7)
               .addGroup(layout.createSequentialGroup()
                  .addGap(6, 6, 6)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(txtReceptorApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(18, 18, 18)
                              .addComponent(txtReceptorApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addComponent(txtReceptorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtPeso))
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtReceptorDNI))
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtReceptorCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                     .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                           .addComponent(jLabel17)
                           .addGroup(layout.createSequentialGroup()
                              .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(364, 364, 364))
                     .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(242, 242, 242))))
               .addComponent(jLabel25)
               .addGroup(layout.createSequentialGroup()
                  .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(163, 163, 163)
                  .addComponent(jLabel10)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(txtEmisorNombre)))
            .addGap(31, 31, 31))
         .addGroup(layout.createSequentialGroup()
            .addGap(52, 52, 52)
            .addComponent(txtEmisorDNI, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(txtEmisorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(txtEmisorDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtLargo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addGap(18, 18, 18)
                  .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(3, 3, 3)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtReceptorApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtReceptorApellidoM, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtReceptorNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtReceptorDNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(txtReceptorCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(35, 35, 35))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
		String dni = txtEmisorDNI.getText();
		Double largo = Double.valueOf(txtLargo.getText());
		Double alto = Double.valueOf(txtAlto.getText());
		Double ancho = Double.valueOf(txtAncho.getText());
		Double peso = Double.valueOf(txtPeso.getText());

		String rApellidoP = txtReceptorApellidoP.getText();
		String rApellidoM = txtReceptorApellidoM.getText();
		String rNombre = txtReceptorNombre.getText();
		String rDNI = txtReceptorDNI.getText();
		String rCelular = txtReceptorCelular.getText();

		List<Double> lista2 = List.of(largo, alto, ancho, peso);
		List<String> lista3 = List.of(rApellidoP, rApellidoM, rNombre, rDNI, rCelular);

		EnvioController.generarVenta(dni, lista2, lista3);

   }//GEN-LAST:event_btnConfirmarActionPerformed

   private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
		// TODO add your handling code here:
   }//GEN-LAST:event_btnCancelarActionPerformed

   private void txtEmisorDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtEmisorDNIFocusLost
		txtEmisorNombre.setText("No existe DNI");
		if (existeCliente()) {
			txtEmisorNombre.setText(clienteDto.getNombre() + ", " + clienteDto.getApellidoP());
		}
   }//GEN-LAST:event_txtEmisorDNIFocusLost

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(RegistroEnvioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(RegistroEnvioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(RegistroEnvioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(RegistroEnvioView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				RegistroEnvioView dialog = new RegistroEnvioView(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnCancelar;
   private javax.swing.JButton btnConfirmar;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel25;
   private javax.swing.JLabel jLabel29;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JTextField txtAlto;
   private javax.swing.JTextField txtAncho;
   private javax.swing.JTextField txtEmisorDNI;
   private javax.swing.JTextField txtEmisorNombre;
   private javax.swing.JTextField txtLargo;
   private javax.swing.JTextField txtPeso;
   private javax.swing.JTextField txtReceptorApellidoM;
   private javax.swing.JTextField txtReceptorApellidoP;
   private javax.swing.JTextField txtReceptorCelular;
   private javax.swing.JTextField txtReceptorDNI;
   private javax.swing.JTextField txtReceptorNombre;
   // End of variables declaration//GEN-END:variables

	private boolean existeCliente() {
		String dni = txtEmisorDNI.getText();
		clienteDto = EnvioController.validarCliente(dni);
		if (clienteDto == null) {
			return false;
		}
		return true;
	}
}
