package uni.curafacil.view;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import uni.curafacil.controller.GCProductoController;
import uni.curafacil.dto.ItemDto;

import uni.curafacil.dto.ProductoDto;

public class GCProductosView extends javax.swing.JDialog {

	private List<ProductoDto> listado;
	private GCProductoController controller;

	public GCProductosView(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		this.setLocationRelativeTo(null);
		this.setResizable(false);
		controller = new GCProductoController();
		cargarDatos();
	}

	private void cargarDatos() {
		listado = controller.getProductos();
		// Cargando los datos
		DefaultTableModel tabla;
		tabla = (DefaultTableModel) tblProductos.getModel();
		tabla.setRowCount(0);
		for (ProductoDto dto : listado) {
			Object[] rowData = {
				dto.getCodigo(),
				dto.getDescripcion(),
				dto.getPrecioCaja(),
				dto.getPrincActivo(),
				dto.getFechaVenc(),
				dto.getStock()
			};
			tabla.addRow(rowData);
		}
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      tblProductos = new javax.swing.JTable();
      jLabel1 = new javax.swing.JLabel();
      txtCantidad = new javax.swing.JTextField();
      btnAceptar = new javax.swing.JButton();
      btnCancelar = new javax.swing.JButton();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
      setTitle("SELECCIONAR PRODUCTO");

      tblProductos.setModel(new javax.swing.table.DefaultTableModel(
         new Object [][] {
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null},
            {null, null, null, null, null, null}
         },
         new String [] {
            "CODIGO", "DESCRIPCION", "PRECIO CAJA", "PRINC ACTIVO", "FEC.VENC.", "STOCK"
         }
      ) {
         Class[] types = new Class [] {
            java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
         };
         boolean[] canEdit = new boolean [] {
            true, false, false, true, false, false
         };

         public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
         }

         public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
         }
      });
      tblProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      tblProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
      jScrollPane1.setViewportView(tblProductos);
      if (tblProductos.getColumnModel().getColumnCount() > 0) {
         tblProductos.getColumnModel().getColumn(0).setResizable(false);
         tblProductos.getColumnModel().getColumn(1).setResizable(false);
         tblProductos.getColumnModel().getColumn(2).setResizable(false);
         tblProductos.getColumnModel().getColumn(3).setResizable(false);
         tblProductos.getColumnModel().getColumn(4).setResizable(false);
         tblProductos.getColumnModel().getColumn(5).setResizable(false);
      }

      jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      jLabel1.setText("Cantidad");

      txtCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      txtCantidad.setText("1");

      btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      btnAceptar.setText("Aceptar");
      btnAceptar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnAceptarActionPerformed(evt);
         }
      });

      btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
      btnCancelar.setText("Cancelar");
      btnCancelar.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnCancelarActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
            .addContainerGap())
         .addGroup(layout.createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
               .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
               .addComponent(txtCantidad)
               .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(14, 14, 14))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
		 this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
		 if (tblProductos.getSelectedRow() == -1) {
			 return;
		 }
		 if (txtCantidad.getText().isBlank()) {
			 return;
		 }
		 if (!UtilView.isInteger(txtCantidad.getText())) {
			 return;
		 }
		 int row = tblProductos.getSelectedRow();
		 ItemDto dto = new ItemDto();
		 dto.setCodigo(listado.get(row).getCodigo());
		 dto.setDescripcion(listado.get(row).getDescripcion());
		 dto.setPrecio(listado.get(row).getPrecioCaja());
		 dto.setCantidad(Integer.valueOf(txtCantidad.getText()));
		 dto.setSubtotal(dto.getCantidad() * dto.getPrecio());
		 Session.put("item", dto);
		 this.dispose();
    }//GEN-LAST:event_btnAceptarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GCProductosView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		/* Create and display the form */
		java.awt.EventQueue.invokeLater(() -> {
			new GCProductosView(new javax.swing.JFrame(), true).setVisible(true);
		});
	}

	/*
    public  Object[] getSelectedRowData() {
        int row = tblProductos.getSelectedRow();
        if (row >= 0) {
            int columnCount = tblProductos.getColumnCount();
            Object[] rowData = new Object[columnCount];
            for (int i = 0; i < columnCount; i++) {
                if (tblProductos.getValueAt(row, i) != null) {
                    rowData[i] = tblProductos.getValueAt(row, i);
                } else {
                    rowData[i] = "";
                }
            }
            return rowData;
        } else {
            return null;
        }
    }
	 */

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton btnAceptar;
   private javax.swing.JButton btnCancelar;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTable tblProductos;
   private javax.swing.JTextField txtCantidad;
   // End of variables declaration//GEN-END:variables
}
